version: '3'
services:
  app:
    container_name: myapp
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
      - "8080:8080"

    environment:
      - MONGO_URL=mongodb+srv://younana121:12345@cluster0.uus7hle.mongodb.net/AnthDB
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    